### ISSUE TITLE
这个是替代PC端的C++还是只是PHP后台服务

### ISSUE THREAD

**Issue by aiuluna** [51wakeup/wakeup-qcloud-sdk#2]
这个是替代PC端的C++还是只是PHP后台服务

**Comment by jingxiang** [comment]
这是业务服务端与腾讯云的两款产品：云通信、直播，进行交互的Java SDK。
与你说的C++、PHP没任何关系，只是腾讯云没有业务服务端的Java SDK，所以自己写了一份并贡献了出来。
@aiuluna

**Comment by aiuluna** [comment]
因为我看腾讯互动直播的服务端是PHP的，那就是说是个业务后台系统，跟PC端或者IOS,ANDROID端无关了。PC端的还是要用C++写客户端。。你们有用web集成么。
@jingxiang

**Comment by jingxiang** [comment]
我们有web集成的，但不是PC端，是微信H5端。关于腾讯云业务相关问题，建议咨询腾讯云官方的技术群。
@aiuluna

**Comment by aiuluna** [comment]
好的，多谢。多问一句，集成的H5端是能发起视频通话并且两边都能看见人吗，类似互动直播的功能？能具有IOS客户端上各种功能的么。
@jingxiang

**Comment by jingxiang** [comment]
@aiuluna 
你说的是连麦吧？web端只能通过旁路直播实现，旁路直播好像是支持两路视频流的，具体你咨询下腾讯云相关人员
