### ISSUE TITLE
您好, 这个和腾讯云tencentcloud-sdk-java 有区别没？

### ISSUE THREAD

**Issue by ttxs0109** [51wakeup/wakeup-qcloud-sdk#6]
https://github.com/TencentCloud/tencentcloud-sdk-java

**Comment by jingxiang** [comment]
@yiyuan0109 
1、这个SDK前，腾讯云应该还没有官方tencentcloud-sdk-java 的API；
2、我看了下tencentcloud-sdk-java 的代码，封装上比较粗暴，请求和返回需要自己处理json对象。

以上。
